// GENERATED FILE — do NOT edit manually.
// Run: flutterfire configure
// This file is generated by the FlutterFire CLI and contains your
// Firebase project configuration. See README for setup instructions.
//
// TODO: Run `flutterfire configure` to regenerate this file with your
// actual Firebase project credentials before running the app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for this platform. '
          'Run flutterfire configure.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXUiKLL1C-aRaPrR0lyA99Kr3_7-GgfTw',
    appId: '1:308784679328:web:e64ce3a5bcc2279a327cc5',
    messagingSenderId: '308784679328',
    projectId: 'pettracker-682e8',
    authDomain: 'pettracker-682e8.firebaseapp.com',
    storageBucket: 'pettracker-682e8.firebasestorage.app',
  );

  // Replace these placeholder values by running: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAK2JJ_zU9x7xNan-z2w6Vgx-YiD4HVoM',
    appId: '1:308784679328:android:f7077d2377f3e0b9327cc5',
    messagingSenderId: '308784679328',
    projectId: 'pettracker-682e8',
    storageBucket: 'pettracker-682e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvkB4_G0nKJiUzAvGOXb3hW9lNiUobt3I',
    appId: '1:308784679328:ios:fa76d306f16d465f327cc5',
    messagingSenderId: '308784679328',
    projectId: 'pettracker-682e8',
    storageBucket: 'pettracker-682e8.firebasestorage.app',
    iosClientId: '308784679328-mm7mv8qabai2ha39clts59j118hqq03b.apps.googleusercontent.com',
    iosBundleId: 'com.pettracker.petTracker',
  );

}